'use strict';

const CONSTANTS = {};

CONSTANTS.SERVER = {
	ONE: 1,
};

CONSTANTS.SERVER_TYPES = {
	API: 'api',
	SOCKET: 'socket',
};

CONSTANTS.OPERATION_TYPE = {
	UPDATE_LAND_TYPE: 1,
	MAKE_LAND_UNAVAILABLE: 2,
};

CONSTANTS.AVAILABLE_AUTHS = {
	ADMIN: 1,
	USER: 2,
	ADMIN_USER: 3
};

CONSTANTS.FILE_UPLOAD_TYPE = {
	PROFILE_IMAGE: 1,
	CHAT_MEDIA: 2,
};

CONSTANTS.TOKEN_TYPES = {
	LOGIN: 1,
	OTP: 2,
	RESET_PASSWORD: 3,
};

CONSTANTS.WORLD_COUNT = 5;
CONSTANTS.WORLD_LAND_COUNT = 8100000;

CONSTANTS.LAND_TYPE = {
	NORMAL: 1,
	PREMIUM: 2,
	EXTRA_PREMIUM: 2,
};

CONSTANTS.ESTATE_TYPE = {
	SMALL: 1,
	MEDIUM: 2,
	LARGE: 3,
	EXTRA_LARGE: 4,
};

CONSTANTS.DATABASE_VERSIONS = {
	ONE: 1,
};

CONSTANTS.USER_TYPE = {
	USER: 1,
	COMPANY: 2,
};

CONSTANTS.PASSWORD_PATTER_REGEX = /^(?=.{6,})(?=.*[a-z])(?=.*[0-9])(?=.*[A-Z])(?=.*[@#$%^&+=]).*$/;

CONSTANTS.NAME_REGEX = /^[a-zA-Z\s]{1,20}[a-zA-Z\s]$/;
CONSTANTS.PHONE_REGEX = /^\+\d{1,3}\d{8,10}$/;
CONSTANTS.ETHEREUM_ADDRESS_REGEX = /^0x[a-fA-F0-9]{40}$/;

CONSTANTS.NORMAL_PROJECTION = {
	__v: 0, isDeleted: 0, createdAt: 0, updatedAt: 0,
};

CONSTANTS.MESSAGES = require('./messages');

CONSTANTS.SECURITY = {
	JWT_SIGN_KEY: 'fasdkfjklandfkdsfjladsfodfafjalfadsfkads',
	BCRYPT_SALT: 8,
	STATIC_TOKEN_FOR_AUTHORIZATION: '58dde3df315587b279edc3f5eeb98145',
};
CONSTANTS.MAP_DEFAULT_MONGO_ID = '6298bbf1c5f9f220b1dd1de2';

CONSTANTS.ERROR_TYPES = {
	DATA_NOT_FOUND: 'DATA_NOT_FOUND',
	BAD_REQUEST: 'BAD_REQUEST',
	MONGO_EXCEPTION: 'MONGO_EXCEPTION',
	ALREADY_EXISTS: 'ALREADY_EXISTS',
	FORBIDDEN: 'FORBIDDEN',
	INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
	UNAUTHORIZED: 'UNAUTHORIZED',
	INVALID_MOVE: 'invalidMove',
};

CONSTANTS.LOGIN_TYPES = {
	METAMASK: 1,
};

CONSTANTS.EMAIL_TYPES = {
	WELCOME_EMAIL: 1,
};

CONSTANTS.EMAIL_SUBJECTS = {
	WELCOME_EMAIL: 'Test email',
};

CONSTANTS.EMAIL_CONTENTS = {
	WELCOME_EMAIL: '<p>Hello<span style="color: #3366ff;"></span>,</p><p>This is test Email.</p><p>Regards,<br>Team CuesZ</p>',
};

CONSTANTS.AVAILABLE_EXTENSIONS_FOR_FILE_UPLOADS = [ 'csv', 'png' ];
CONSTANTS.ALLOWED_EXTENSIONS_FOR_PROFILE_IMAGE = [ 'jpg', 'png', 'jpeg', 'JPG', 'PNG', 'JPEG', 'webp', 'WEBP' ];

CONSTANTS.GENDER = {
	MALE: 'Male',
	FEMALE: 'Female',
	OTHERS: 'Other',
};

CONSTANTS.OTP_EXPIRIED_TIME_IN_SECONDS = 300;

CONSTANTS.USER_STATUS = {
	DELETED: 1,
};

CONSTANTS.S3_DEFAULT_IMAGE = 'default.png';

CONSTANTS.REDIS_EXPIRE_TIME_IN_SEC = 10800;
CONSTANTS.REDIS_EVENTS = {
	TEST: 'test',
	LAND_UPDATED: 'landUpdated',
	SELL_LAND_CONFIRMATION: 'sellLandConfirmation',
	LOCK_LAND: 'lockLand',
	MINT_LAND: 'mintLand'
};

CONSTANTS.MESSAGE_TYPE = {
	MESSAGE: 1,
	AUDIO_CALL: 2,
	VIDEO_CALL: 3,
};

CONSTANTS.MESSAGE_TYPES = {
	TEXT: 1,
	IMAGE: 2,
	VIDEO: 3,
	DOCUMENT: 4,
};

CONSTANTS.CALL_STATUS = {
	PENDING: 1,
	ACCEPTED: 2,
	REJECTED: 3,
};

CONSTANTS.PROFILE_VISIBLE_STATUS = {
	NONE: 1,
	ALL: 2,
	SPECIFIC: 3,
	// EXCEPT: 4
};

CONSTANTS.SOCKET_EVENTS = {
	TEST: 'test',
	DISCONNECT: 'disconnect',

	CREATE_BID: 'createBid',

	CANCEL_AUTO_BID: 'cancelAutoBid',

	AUCTION_ADDED: 'auctionAdded',

	JOIN_ROOM: 'joinRoom',
	WALLET_UPDATED: 'walletUpdated',

	AUTO_BID_UPDATED: 'autoBidUpdated',

	AUCTION_UPDATED: 'auctionUpdated',
	BIDS_SPENT_HISTORY: 'bidSpentHistory',
};

CONSTANTS.SECTION_TYPE = {
	AUCTION_PAGE: 1,
	AUCTION_DETAILED_PAGE: 2,
	TOP_AUCTION: 3
};

CONSTANTS.SOCKET_ROOMS = {
	AUCTION_PAGE: 'AUCTION_PAGE',
	TOP_AUCTION: 'TOP_AUCTION',
	AUCTION_ROOM: 'AUCTION_ROOM'
};

CONSTANTS.AUTO_BID_DELAY_TIME = 2; // IN SECONDS

CONSTANTS.PAGINATION = {
	SKIP: 0,
	LIMIT: 10,
	TOP_AUCTION_LIMIT: 8
};

CONSTANTS.COIN_FLIP_TYPE = {
	HEADS: 1,
	TAILS: 2
};

CONSTANTS.GAME_STATUS = {
	MATCH_MAKING_STARTED: 1,
	ON_GOING: 2,
	FINISHED: 3
};

CONSTANTS.GAME_PLAYER_STATUS = {
	PLAYING: 1,
	LEFT_KNOCKOUT: 2
};

CONSTANTS.CRASH_GAME_STATUS = {
	WAITING_ROOM: 1,
	GAMEPLAY: 2,
	FINISHED: 3
};

CONSTANTS.WAITING_TIMER= 30; // timer will be in seconds

CONSTANTS.TIMER_TYPE = {
	MATCH_MAKING_TIMER: 1,
	PLAYER_TURN: 2,
	APPLY_BET_TIMER: 3
};

CONSTANTS.LINE_TYPE = {
	LINE_8: [ 5, 3, 1.5, 1, 0.5, 0.3, 0.5, 1, 1.5, 3, 5 ],
	LINE_9: [ 10, 5, 2, 1.5, 0.3, 0.3, 1.5, 2, 1.5, 2, 10 ],
	LINE_10: [ 25, 5, 2, 1.5, 0.5, 0.3, 0.5, 1.5, 2, 5, 25 ],
	LINE_11: [ 25, 5, 3, 2, 0.5, 0.3, 0.3, 0.5, 2, 3, 5, 25 ],
	LINE_12: [ 33, 10, 3, 2, 1.5, 0.5, 0.3, 0.5, 1.5, 2, 3, 10, 33 ],
	LINE_13: [ 41, 15, 5, 3, 1.5, 0.5, 0.3, 0.3, 0.5, 1.5, 3, 5, 15, 41 ],
	LINE_14: [ 41, 15, 5, 3, 1.5, 1, 0.5, 0.3, 0.5, 1, 1.5, 3, 5, 15, 41 ],
	LINE_15: [ 88, 18, 10, 5, 3, 1.5, 0.5, 0.3, 0.3, 0.5, 1.5, 3, 5, 10, 18, 88 ],
	LINE_16: [ 110, 41, 10, 5, 3, 1.5, 1, 0.5, 0.3, 0.5, 1, 1.5, 3, 5, 10, 41, 110 ],
};

CONSTANTS.AUCTION_STATUS = {
	PENDING: 1, // awaiting bidding
	ACTIVE: 2, // bidding active
	ENDED: 3, // bidding ended
	CANCEL: 4,
	PENDING_ACTIVE: 5
};

CONSTANTS.PRODUCT_PURCHASE_STATUS = {
	PENDING: 1, // awaiting bidding
	PURCHASED: 2, // bidding active
	EXPIRED: 3, // bidding ended
};

CONSTANTS.BID_STATUS = {
	CONFIRMED: 1,
	REFUNDED: 2
};

CONSTANTS.BID_INC_VALUE= 1;

CONSTANTS.BID_TIMER = 30; // in seconds

CONSTANTS.BIDS = {
	AUTO: 1,
	MANUAL: 2
};

CONSTANTS.NOTIFICATION_TYPE = {
	RESERVE_PRICE_REACHED: 1,
	NEW_BID_PLACED: 2,
	AUTOMATIC_BID_RAND_OUT: 3,
	BID_TIME_LEFT: 4,
	WINNER: 5,
	AUCTION_ENDED: 6,
	NEW_USER_JOINED: 7,
	AUCTION_STARTED: 8,
	BID_PLAN_PURCHASED: 9,
	CONTACTED_SUPPORT: 10
};

CONSTANTS.PUSH_ALERT_LIMITS = {
	TITLE_LENGTH: 64,
	BODY_LENGTH: 192,
};


CONSTANTS.BID_CREDIT_TYPES = {
	PURCHASE: 1,
	ADMIN_GIFT: 2,
	REFERRAl: 3,
	SIGNUP_BONUS: 4,
	REFUND: 5,
	SOCIAL_MEDIA_SHARE: 6,
};

CONSTANTS.REFERRAL_STATUS = {
	PENDING: 1,
	COMPLETED: 2,
};

CONSTANTS.METHODS_TYPE = {
	POST: 'post',
	GET: 'get',
	PUT: 'put',
	DELETE: 'delete',
	PATCH: 'patch'
};


CONSTANTS.COUNTER_NAME = {
	auctions: 'auctionCounter',
	referralPacks: 'referralPackCounter',
	bidPlans: 'bidPlanCounter',
	bidSpentHistory: 'bidSpentHistoryCounter',
	userProducts: 'userProductCounter',
	users: 'userCounter',
	products: 'productCounter',
	bidCreditHistory: 'bidCreditHistoryCounter',
	referralHistory: 'referralHistoryCounter',
	bidPlanTransactions: 'bidPlanTransactionsCounter',
	userInvoices: 'userInvoiceCounter',
};

CONSTANTS.BID_PLAN_TYPE = {
	REGULAR: 1,
	CUSTOM: 2,
};

CONSTANTS.BID_PLAN_PURCHASE_STATUS = {
	PENDING: 1,
	COMPLETED: 2,
	FAILED: 3,
};

CONSTANTS.FILE_TYPE = {
	CMS: 1,
	PRODUCT: 2,
	AUCTION: 3,
};

CONSTANTS.FUEL_TYPE = {
	DIESEL: 1,
	PETROL: 2,
	CNG: 3,
	ELECTRIC: 4,
	HYBRID: 5,
};

CONSTANTS.GEARBOX_TYPE = {
	MANUAL: 1,
	AUTOMATIC: 2,
};

CONSTANTS.INVOICE_TYPE = {
	BID_PLAN: 1,
	BID_CREDIT: 2,
	USER_PRODUCT: 3,
};

CONSTANTS.SOCIAL_MEDIA_PLATFORMS = {
	FACEBOOK: 1,
	TWITTER: 2,
	LINKEDIN: 3,
	INSTAGRAM: 4,
	WHATSAPP: 5,
}; 

CONSTANTS.CAR_BODY_TYPE = {
	SEDAN: 1,
	CROSSOVER: 2,
	SUV: 3,
	HATCHBACK: 4,
	STATION_WAGON: 5,
	COUPE: 6,
	PICKUP_TRUCK: 7,
	MINIVAN: 8,
	ROADSTER: 9,
	VAN: 10,
	SPORTS_CAR: 11,
	SUPERCAR: 12,
	LUXURY_CAR: 13,
	CONVERTIBLE: 14,
	MUSCLE_CAR: 15,
	MICROCAR: 16,
	CAMPER_VAN: 17,
	MINITRUCK: 18,
	LIMOUSINE: 19,
	TRUCK: 20,
	HOT_HATCH: 21,
	UTE: 22,
	PONY_CAR: 23,
	MILITARY_VEHICLE: 24,
	DRAGSTER: 25,
	GRAND_TOURER: 26,
	SHOOTING_BRAKE: 27,
	HOT_ROD: 28,
	LOW_RIDER: 29,
};

module.exports = CONSTANTS;
